# Generated by Django 5.2 on 2025-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('neurologist', 'Neurologist')], max_length=15),
        ),
    ]
