# Generated by Django 5.2 on 2025-05-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_doctor_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_cin',
            field=models.CharField(null=True),
        ),
    ]
