# Generated by Django 5.2 on 2025-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user__cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_cin',
            field=models.CharField(default='AB123456', null=True),
        ),
    ]
