# Generated by Django 5.2.1 on 2025-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user__cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, default='212612345600', max_length=12, null=True),
        ),
    ]
