
services:

  web:
    build:
      context: .
      dockerfile: ./tests/app/dockerfile
    container_name: dev_app
    env_file:
      - .env
    volumes:
      - static_volume:/app/static 
      - media_volume:/app/media 

    expose:
      - 8000
    
    restart: always
    networks:
      - dev_network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/users/auth/login/"] # Or any endpoint that signals app readiness
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    image: postgres:17
    container_name: dev_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    networks:
      - dev_network
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: always 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s



  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    container_name: nginx_dev
    ports:
      - 80:80
      - 443:443 
    volumes:
      - static_volume:/usr/share/app/static/
     

    depends_on:
      - web
    restart: always 
    networks:
      - dev_network
   
    
volumes:
  postgres_data_dev:
  static_volume:
  media_volume:
networks:
  dev_network:
    driver: bridge
